config/routes.rb
Rails.application.routes.draw do
  # Subject Headings browser - for exploring aboutnesses
  resources :subject_headings, only: [:index, :show] do
    collection do
      get :autocomplete
    end
  end

  get "dashboard/index"
  get "dashboard/aboutness", to: "dashboard#aboutness"
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resource :user_settings, only: [:edit, :update], path: 'settings'

  get 'manifestations/show'

  get 'manifestations/approve'

  resources :tocs do
    collection do
      post :create_multiple
      get :search
      get :gutenberg_proxy
    end
    member do
      get :browse_scans
      get :download
      post :mark_pages
      post :mark_transcribed
      post :verify
      post :auto_match_subjects
      get :review_authors
    end
  end
  get 'publications/search'

  get 'publications/details' => "publications#details"

  get 'publications/browse'

  get 'publications/savetoc'

  post 'tocs/do_ocr' => "tocs#do_ocr"

  # Aboutnesses - nested under embodiments
  resources :embodiments, only: [] do
    resources :aboutnesses, only: [:index, :new, :create] do
      collection do
        post :search
      end
    end
  end

  # Aboutnesses - destroy and verify don't need embodiment nesting
  resources :aboutnesses, only: [:destroy] do
    member do
      patch :verify
    end
  end

  # Help page
  get 'help', to: 'help#index'

  # Public (unauthenticated) verified TOCs
  get 'browse', to: 'public_tocs#index', as: :browse_tocs
  get 'browse/:id', to: 'public_tocs#show', as: :browse_toc
  get 'browse/:id/download', to: 'public_tocs#download', as: :download_browse

  # Locale switching
  get 'locale/:locale', to: 'application#switch_locale', as: :locale

  # People (authors/creators) management
  resources :people, only: [:index, :show, :new, :create, :edit, :update] do
    collection do
      post :search_viaf
      post :search_wikidata
      post :search_loc
      post :search_all
      get :fetch_details
      post :match
      post :accept_parent_match
      post :undo_match
    end
  end

  root 'home#index'
end

app/controllers/publications_controller.rb
class PublicationsController < ApplicationController
  @@olclient = OpenLibrary::Client.new
  @@gutendex_client = Gutendex::Client.new

  def search
    search_params = params[:search] || params[:q]
    @source = params[:source] || 'openlibrary'

    if search_params.present? || params[:title].present? || params[:author].present?
      # Add pagination parameters
      @current_page = (params[:page] || 1).to_i
      @per_page = (params[:per_page] || 20).to_i

      case @source
      when 'gutendex'
        search_gutendex(search_params)
      else # 'openlibrary'
        search_openlibrary(search_params)
      end
    end
  end

  def details
    @olkey = params[:olkey]
  end

  def browse
  end

  def savetoc
  end

  def olclient
    @@olclient
  end

  private

  def search_openlibrary(search_params)
    # Determine if we should filter for full-text only
    fulltext_only = params[:fulltext_only] == '1' || params[:fulltext_only] == 'true'

    # Build search query
    search_opts = {}
    search_opts[:title] = params[:title] if params[:title].present?
    search_opts[:author] = params[:author] if params[:author].present?
    if search_params.present? && params[:title].blank? && params[:author].blank?
      search_opts[:query] = search_params
    end
    search_opts[:has_fulltext] = fulltext_only
    search_opts[:page] = @current_page
    search_opts[:per_page] = @per_page

    @results = olclient.search(**search_opts)
    @any_fulltext = false
    if @results.present?
      @num_results = @results['numFound']
      @total_pages = (@num_results.to_f / @per_page).ceil
      @results = @results['docs']

      # Filter for public ebook access if fulltext_only is enabled
      if fulltext_only
        @results = @results.select { |r| r['has_fulltext'] && r['ebook_access'] == 'public' }
      end

      # Filter out publications that already have ToCs
      @results = filter_existing_tocs_openlibrary(@results)

      @results.each do |r|
        logger.info "#{r['title']} / #{r['author_name']} #{(r['has_fulltext'] && r['ebook_access'] == 'public') ? '[ebook!]' : 'metadata only'}"
        @any_fulltext = true if r['has_fulltext'] && r['ebook_access'] == 'public'
      end
    end
  end

  def search_gutendex(search_params)
    # Build search query for Gutendex
    search_opts = {}
    if params[:title].present? && params[:author].present?
      # Combine title and author in general search
      search_opts[:query] = "#{params[:title]} #{params[:author]}"
    elsif params[:title].present?
      search_opts[:query] = params[:title]
    elsif params[:author].present?
      search_opts[:query] = params[:author]
    elsif search_params.present?
      search_opts[:query] = search_params
    end

    # Gutendex only has public domain books, so all results have fulltext
    search_opts[:page] = @current_page
    search_opts[:per_page] = @per_page

    response = gutendex_client.search(**search_opts)
    @any_fulltext = true # All Gutendex books have fulltext
    if response.present?
      @num_results = response['numFound']
      @total_pages = (@num_results.to_f / @per_page).ceil
      @results = response['results'] || []

      # Transform Gutendex results to a common format
      @results = @results.map do |book|
        {
          'id' => book['id'],
          'title' => book['title'],
          'author_name' => book['authors']&.map { |a| a['name'] },
          'has_fulltext' => true,
          'ebook_access' => 'public',
          'source' => 'gutendex',
          'formats' => book['formats']
        }
      end

      # Filter out publications that already have ToCs
      @results = filter_existing_tocs_gutendex(@results)
    end
  end

  def gutendex_client
    @@gutendex_client
  end

  # Filter out search results that already have ToC entries in the database
  # @param results [Array<Hash>] OpenLibrary search results
  # @return [Array<Hash>] Filtered results without existing ToCs
  def filter_existing_tocs_openlibrary(results)
    return results if results.blank?

    # Extract edition keys from results
    edition_keys = results.filter_map do |book|
      edition = book.dig('editions', 'docs')&.first
      edition&.dig('key')&.split('/')&.last
    end

    return results if edition_keys.empty?

    # Build book URIs to check against existing ToCs
    book_uris = edition_keys.map { |key| "http://openlibrary.org/books/#{key}" }

    # Query existing ToCs with these URIs
    existing_uris = Toc.where(book_uri: book_uris).pluck(:book_uri).to_set

    # Filter out results that have existing ToCs
    results.reject do |book|
      edition = book.dig('editions', 'docs')&.first
      edition_key = edition&.dig('key')&.split('/')&.last
      next false unless edition_key

      book_uri = "http://openlibrary.org/books/#{edition_key}"
      existing_uris.include?(book_uri)
    end
  end

  # Filter out Gutendex results that already have ToCs
  # @param results [Array<Hash>] Gutendex search results
  # @return [Array<Hash>] Filtered results without existing ToCs
  def filter_existing_tocs_gutendex(results)
    return results if results.blank?

    # Build book URIs for Gutendex books
    book_uris = results.map { |book| "https://www.gutenberg.org/ebooks/#{book['id']}" }

    # Query existing ToCs with these URIs
    existing_uris = Toc.where(book_uri: book_uris).pluck(:book_uri).to_set

    # Filter out results that have existing ToCs
    results.reject do |book|
      book_uri = "https://www.gutenberg.org/ebooks/#{book['id']}"
      existing_uris.include?(book_uri)
    end
  end
end

app/helpers/publications_helper.rb
module PublicationsHelper
end

app/views/publications/_ol_results.html.haml
- unless @results.blank?
  #multi-select-controls
    = form_tag create_multiple_tocs_path, method: :post, id: 'bulk-toc-form' do
      = hidden_field_tag :source, @source
      .selection-info
        %span#selection-count.selection-count 0 selected
      = button_tag t('publications.search.make_tocs_button'), type: 'submit', class: 'btn btn-success btn-lg hidden-initially', id: 'bulk-create-btn'

  .search-results-grid
    - @results.each do |book|
      - if book['source'] == 'gutendex'
        - book_id = book['id']
        - can_make_toc = true
        .book-card{data: {book_id: book_id, source: 'gutendex'}}
          .card-checkbox
            = check_box_tag "book_ids[]", book_id, false, class: 'book-checkbox', data: { title: book['title'], authors: Array(book['author_name']).join(', '), source: 'gutendex' }
          - if book['formats'] && book['formats']['image/jpeg']
            = image_tag book['formats']['image/jpeg'], alt: book['title'], class: 'book-cover', loading: 'lazy', onerror: "this.style.display='none'"
          - else
            .book-cover.placeholder
              .cover-placeholder-content
                %span.glyphicon.glyphicon-book
          .card-header
            .edition-key
              %code= "PG-#{book_id}"
            .fulltext-badge
              %span.label.label-success= t('publications.search.fulltext_labels.public')
          .card-body
            %h3.book-title= book['title']
            - if book['author_name']
              .book-authors
                %small= t('publications.search.by_authors', authors: Array(book['author_name']).join(', '))
          .card-footer
            = link_to t('publications.search.make_toc_button'), new_toc_path(params: {pg_book_id: book_id, from: :gutendex}), class: 'btn btn-primary btn-block'
      - else
        - edition = book.dig('editions', 'docs')&.first
        - edition_key = edition&.dig('key')&.split('/')&.last
        - can_make_toc = book['has_fulltext'] && book['ebook_access'] == 'public' && edition_key
        .book-card{data: {book_id: edition_key, source: 'openlibrary'}, class: (can_make_toc ? '' : 'disabled')}
          - if can_make_toc
            .card-checkbox
              = check_box_tag "book_ids[]", edition_key, false, class: 'book-checkbox', data: { title: book['title'], authors: Array(book['author_name']).join(', '), source: 'openlibrary' }
          - if edition && edition['cover_i']
            = image_tag "https://covers.openlibrary.org/b/id/#{edition['cover_i']}-M.jpg", alt: book['title'], class: 'book-cover', loading: 'lazy', onerror: "this.style.display='none'"
          - else
            .book-cover.placeholder
              .cover-placeholder-content
                %span.glyphicon.glyphicon-book
          .card-header
            .edition-key
              %code= edition_key || book['key']
            .fulltext-badge
              - if book['has_fulltext']
                - if book['ebook_access'] == 'public'
                  %span.label.label-success= t('publications.search.fulltext_labels.public')
                - else
                  %span.label.label-warning= t('publications.search.fulltext_labels.restricted')
              - else
                %span.label.label-default= t('publications.search.fulltext_labels.metadata_only')
          .card-body
            %h3.book-title= book['title']
            - if book['author_name']
              .book-authors
                %small= t('publications.search.by_authors', authors: Array(book['author_name']).join(', '))
          .card-footer
            - if can_make_toc
              = link_to t('publications.search.make_toc_button'), new_toc_path(params: {ol_book_id: edition_key, from: :openlibrary}), class: 'btn btn-primary btn-block'
            - elsif !edition_key
              %span.text-muted= t('publications.search.no_edition')
            - else
              %span.text-muted= t('publications.search.no_fulltext')
- else
  - if params[:search].present? || params[:title].present? || params[:author].present?
    .search-results-empty
      .empty-icon 📚
      %p.alert.alert-info= t('publications.search.nothing_found')

:javascript
  // Use event delegation for dynamic elements
  // Handle checkbox changes
  $(document).on('change', '.book-checkbox', function() {
    var card = $(this).closest('.book-card');
    if ($(this).is(':checked')) {
      card.addClass('selected');
    } else {
      card.removeClass('selected');
    }

    // Update selection count
    var count = $('.book-checkbox:checked').length;
    $('#selection-count').text(count + ' selected');
    var btn = $('#bulk-create-btn');
    if (count > 0) {
      btn.removeClass('hidden-initially').attr('style', '');
    } else {
      btn.addClass('hidden-initially').attr('style', 'display: none;');
    }
  });

  // Make entire card clickable (toggle checkbox)
  $(document).on('click', '.book-card', function(e) {
    // Don't toggle if clicking on links or the checkbox itself
    if ($(e.target).is('a') || $(e.target).is('input[type="checkbox"]')) {
      return;
    }
    var checkbox = $(this).find('.book-checkbox');
    if (checkbox.length > 0) {
      checkbox.prop('checked', !checkbox.prop('checked')).trigger('change');
    }
  });

  // Handle form submission
  $(document).on('submit', '#bulk-toc-form', function(e) {
    var checked = $('.book-checkbox:checked').map(function() { return this.value; }).get();

    if (checked.length === 0) {
      e.preventDefault();
      alert('Please select at least one book to create TOCs for.');
      return false;
    }

    // Remove any previously injected inputs to avoid duplicates
    $(this).find('input[name="book_ids[]"]').remove();

    // Inject hidden inputs for each selected book id
    checked.forEach(function(id) {
      $('<input>').attr({ type: 'hidden', name: 'book_ids[]', value: id }).appendTo('#bulk-toc-form');
    });

    return true;
  });

app/views/publications/_results.html.haml
- unless @results.blank?
  %table{ class: 'table' }
    - @results.each do |book|
      %tr
        %td= "#{book[:key]}"
        %td= "#{book.title} / #{book.author_name}" 
        %td
          - if book.has_fulltext
            = link_to 'Make ToC!', new_toc_path(:params => {book_uri: book[:key]})
          - else
            = '[metadata only]'
- else
  = "Nothing found!"

app/views/publications/browse.html.haml
%h1 Publications#browse
%p Find me in app/views/publications/browse.html.haml

app/views/publications/details.html.haml
%h1 Publications#details
%p TBD: details for Open Library key #{@olkey}

app/views/publications/savetoc.html.haml
%h1 Publications#savetoc
%p Find me in app/views/publications/savetoc.html.haml

app/views/publications/search.html.haml
.row
  .col-xs-12
    .search-header
      %h1= t('publications.search.title')
      %p.search-description= t('publications.search.description')

    .search-form-container
      = form_tag publications_search_path, :method => 'get', :id => 'publications_search' do
        / Main horizontal search bar
        .search-bar-horizontal
          .search-input-group
            = text_field_tag :search, params[:search], class: 'form-control search-input-main', placeholder: t('publications.search.form.general_search_placeholder')
            = submit_tag t('publications.search.form.search_button'), :name => nil, class: 'btn btn-primary btn-search'

          .search-actions
            %button.btn.btn-default{type: 'button', id: 'toggle-advanced', 'data-toggle' => 'collapse', 'data-target' => '#advanced-search'}
              %span.glyphicon.glyphicon-cog
              = t('publications.search.form.advanced_search')
            = button_tag t('publications.search.multi_select_button'), type: 'button', class: 'btn btn-default', id: 'toggle-multiselect', style: 'display: none;'

        / Advanced search collapsible section
        #advanced-search.collapse{class: (params[:title].present? || params[:author].present? || params[:source] == 'gutendex' || params[:fulltext_only] == '1') ? 'in' : ''}
          .advanced-search-panel
            .row
              .col-md-4
                .form-group
                  = label_tag :title, t('publications.search.form.title_search_label'), class: 'control-label-sm'
                  = text_field_tag :title, params[:title], class: 'form-control input-sm', placeholder: t('publications.search.form.title_search_placeholder')

              .col-md-4
                .form-group
                  = label_tag :author, t('publications.search.form.author_search_label'), class: 'control-label-sm'
                  = text_field_tag :author, params[:author], class: 'form-control input-sm', placeholder: t('publications.search.form.author_search_placeholder')

              .col-md-4
                .form-group
                  = label_tag :source, t('publications.search.form.source_label'), class: 'control-label-sm'
                  .source-radios
                    = label_tag 'source_openlibrary', class: 'radio-inline' do
                      = radio_button_tag :source, 'openlibrary', (@source.nil? || @source == 'openlibrary'), id: 'source_openlibrary'
                      = t('publications.search.form.source_openlibrary')
                    = label_tag 'source_gutendex', class: 'radio-inline' do
                      = radio_button_tag :source, 'gutendex', (@source == 'gutendex'), id: 'source_gutendex'
                      = t('publications.search.form.source_gutendex')

            .row
              .col-md-12
                .form-group#fulltext-only-group
                  = check_box_tag :fulltext_only, '1', params[:fulltext_only] == '1'
                  = label_tag :fulltext_only, t('publications.search.form.fulltext_only_label')
                  = help_tooltip t('publications.search.form.fulltext_only_tooltip')

    - if @num_results
      %p.text-muted
        = t('publications.search.form.results_found', count: @num_results)
        - if @total_pages && @total_pages > 1
          = "(#{t('publications.search.page_info', current: @current_page, total: @total_pages)})"

    #results
      != render partial: 'ol_results', locals: { :results => @results}

    - if @total_pages && @total_pages > 1
      .pagination-controls.text-center{style: 'margin: 20px 0;'}
        %nav
          %ul.pagination
            - if @current_page > 1
              %li
                = link_to '«', publications_search_path(search: params[:search], title: params[:title], author: params[:author], fulltext_only: params[:fulltext_only], source: params[:source], page: @current_page - 1)
            - else
              %li.disabled
                %span «

            - window_start = [@current_page - 2, 1].max
            - window_end = [window_start + 4, @total_pages].min
            - window_start = [window_end - 4, 1].max

            - if window_start > 1
              %li
                = link_to '1', publications_search_path(search: params[:search], title: params[:title], author: params[:author], fulltext_only: params[:fulltext_only], source: params[:source], page: 1)
              - if window_start > 2
                %li.disabled
                  %span ...

            - (window_start..window_end).each do |page|
              - if page == @current_page
                %li.active
                  %span= page
              - else
                %li
                  = link_to page, publications_search_path(search: params[:search], title: params[:title], author: params[:author], fulltext_only: params[:fulltext_only], source: params[:source], page: page)

            - if window_end < @total_pages
              - if window_end < @total_pages - 1
                %li.disabled
                  %span ...
              %li
                = link_to @total_pages, publications_search_path(search: params[:search], title: params[:title], author: params[:author], fulltext_only: params[:fulltext_only], source: params[:source], page: @total_pages)

            - if @current_page < @total_pages
              %li
                = link_to '»', publications_search_path(search: params[:search], title: params[:title], author: params[:author], fulltext_only: params[:fulltext_only], source: params[:source], page: @current_page + 1)
            - else
              %li.disabled
                %span »

    %p

:javascript
  $(document).ready(function() {
    var multiselectActive = false;

    // Hide/show fulltext_only checkbox based on source selection
    function updateFulltextOnlyVisibility() {
      var source = $('input[name="source"]:checked').val();
      if (source === 'gutendex') {
        $('#fulltext-only-group').hide();
      } else {
        $('#fulltext-only-group').show();
      }
    }

    // Initialize visibility on page load
    updateFulltextOnlyVisibility();

    // Update visibility when source changes
    $('input[name="source"]').change(function() {
      updateFulltextOnlyVisibility();
    });

    // Multi-select functionality is now handled in _ol_results partial

  });

app/views/publications/search.js.erb
$("#results").html("<%= escape_javascript(render("ol_results")) %>");